---
image:
  repository: k8s.gcr.io/k8s-dns-node-cache
  pullPolicy: IfNotPresent
  tag: 1.15.13

imagePullSecrets: []

config:
  localDnsIp: 169.254.20.11
  upstreamDns: __PILLAR__UPSTREAM__SERVERS__ # defaults to /etc/resolv.conf
  upstreamDnsUseTcp: true
  enableLogging: true

useHostNetwork: true

updateStrategy:
  rollingUpdate:
    maxUnavailable: 10%

priorityClassName: system-node-critical
podAnnotations: {}
podSecurityContext: {}

securityContext:
  privileged: true

readinessProbe:

serviceAccount:
  create: true
  annotations: {}
  name: ""

nodeSelector: {}
affinity: {}

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists

resources:
  requests:
    cpu: 30m
    memory: 50Mi

metrics:
  prometheusScrape: "true"
  port: 9253

skipTeardown: true