---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-local-dns.fullname" . }}
  labels:
    {{- include "node-local-dns.labels" . | nindent 4 }}
data:
  Corefile: |-
    {{- $localDnsIp := .Values.config.localDnsIp -}}
    {{- $metricsPort := .Values.metrics.port -}}

    {{- range $zone := .Values.config.zones }}
    {{ $zone | keys | first }} {
    {{- range $zone }}
      {{- if .plugins.errors }}
      errors
      {{- end }}
      cache {{ .plugins.cache.parameters }} {
        {{- if .plugins.cache.denial }}
        denial {{ .plugins.cache.denial.size }} {{ if .plugins.cache.denial.ttl }} {{ .plugins.cache.denial.ttl }} {{ end }}
        {{- end }}
        {{- if .plugins.cache.success }}
        success {{ .plugins.cache.success.size }} {{ if .plugins.cache.success.ttl }} {{ .plugins.cache.success.ttl }} {{ end }}
        {{- end }}
        {{- if .plugins.cache.prefetch }}
        prefetch {{ .plugins.cache.prefetch.amount }} {{ if .plugins.cache.prefetch.duration }} {{ .plugins.cache.prefetch.duration }} {{ end }} {{ if .plugins.cache.prefetch.percentage }} {{ .plugins.cache.prefetch.percentage }} {{ end }}
        {{- end }}
        {{- if .plugins.cache.server_stale }}
        serve_stale
        {{- end }}
      }
      {{- if .plugins.reload }}
      reload
      {{- end }}
      {{- if .plugins.log }}
      log . {{ default "combined" .plugins.log.format }} {
        class {{ .plugins.log.classes }}
      }
      {{- end }}
      {{- if .plugins.debug }}
      debug
      {{- end }}
      loop
      bind {{ $localDnsIp }}
      forward . {{ .plugins.forward.parameters }} {
      {{- if .plugins.forward.policy }}
        policy {{ .plugins.forward.policy }}
      {{- end }}
      {{- if .plugins.forward.force_tcp }}
        force_tcp
      {{- end }}
      {{- if .plugins.forward.prefer_udp }}
        prefer_udp
      {{- end }}
      {{- if .plugins.forward.max_fails }}
        max_fails {{ .plugins.forward.max_fails }}
      {{- end }}
      {{- if .plugins.forward.expire }}
        expire {{ .plugins.forward.expire }}
      {{- end }}
      {{- if .plugins.forward.health_check }}
        expire {{ .plugins.forward.health_check }}
      {{- end }}
      {{- if .plugins.forward.except }}
        except {{ .plugins.forward.except }}
      {{- end }}
      }
      {{- if .plugins.prometheus }}
      prometheus :{{ $metricsPort }}
      {{- end }}
      {{- if .plugins.health }}
      health {{ $localDnsIp }}:{{ .plugins.health.port }}
      {{- end }}
    {{- end }}
    }
    {{- end }}
